### ISSUE TITLE
Consistency with HashMap: missing `values` iterator.

### ISSUE THREAD

**Issue by eddyb** [bluss/ordermap#17]
I'm trying to use `ordermap` to fix the non-determinism in rustbuild in a useful (order-preserving) way, and I had to replace `.values()` with `.iter().map(|(_, r)| r)` - it's close, but not a drop-in replacement.

**Comment by bluss** [comment]
Ok, values and values_mut should definitely be added so that it's a drop in. As noted somewhere, std HashMap's Entry has two type parameters and ours has three, which is a not yet fixed discrepancy
