### ISSUE TITLE
32bit support?

### ISSUE THREAD

**Issue by chpio** [bluss/ordermap#20]
hi,

is 32bit support on the roadmap? Im building a webapp and discovered that ordermap fails at compile time. I guess that's because of web/emscripten being a 32bit platform.

```
warning: this expression will panic at run-time
   --> .../.cargo/registry/src/github.com-1ecc6299db9ec823/ordermap-0.2.7/src/lib.rs:144:29
    |
144 | 
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^ attempt to shift left with overflow
```

**Comment by bluss** [comment]
Thanks for the report! Sure, it should be supported but I didn't give it enough thought evidently, I think I can see what the issue is.

**Comment by bluss** [comment]
cc @eddyb look, it's not very mature in this crate. :/

**Comment by eddyb** [comment]
@bluss I ended up not being able to use ordermap because I misread the code and needed a manual sort.
