### ISSUE TITLE
Feature request: index_of(&self, key: &Q)

### ISSUE THREAD

**Issue by garro95** [bluss/ordermap#29]
A method that returns the index of the entry stored for `key`, if it is present, else None.
I would suggest a signature like:
`index_of(&self, key: &Q) -> Option<usize>`

**Comment by bluss** [comment]
It already exists: [`get_pair_index`](https://docs.rs/ordermap/0.2.10/ordermap/struct.OrderMap.html#method.get_pair_index) with matching mut method.

**Comment by garro95** [comment]
I know but I think it could be a little bit more ergonomic and very easy to implement
