### ISSUE TITLE
any idea how to return an iterator of a OrderMap value?

### ISSUE THREAD

**Issue by jonathanstrong** [bluss/ordermap#38]
Hey,

Thank you for your work on this great library. 

I have been banging my head trying to figure out how to return an Iterator with `impl Trait` if the collection is in an OrderMap. Do you know how to solve this? (There many not be any way.)

Example: 

```rust
#![feature(conservative_impl_trait)]

extern crate ordermap;
extern crate uuid;

use ordermap::OrderMap;
use uuid::Uuid;

struct Map<T> {
    items: OrderMap<Uuid, Vec<T>>
}

impl<T> Map<T> {
    fn iter_key<'a>(&'a self, k: &'a Uuid) -> impl Iterator<Item = &'a T> + 'a {
        self.items.get(k)
            .iter()
            .flat_map(|xs| {
                xs.iter()
            })
    }
}
```
Note: I used the `iter` method on the `Option<&V>` returned from `get` but have also tried several other approaches. Also, the `+ 'a` may or may not be necessary - I have no idea what it does, but it solved some of my earlier iterator problems after I found it suggested on a github issue. 

The approach above results in the error: 

```
error[E0597]: borrowed value does not live long enough
  --> src/main.rs:15:9
   |
15 |         self.items.get(k)
   |         ^^^^^^^^^^^^^^^^^ does not live long enough
...
20 |     }
   |     - temporary value only lives until here
   |
note: borrowed value must be valid for the lifetime 'a as defined on the method body at 14:5...
  --> src/main.rs:14:5
   |
14 | /     fn iter_key<'a>(&'a self, k: &'a Uuid) -> impl Iterator<Item = &'a T> + 'a {
15 | |         self.items.get(k)
16 | |             .iter()
17 | |             .flat_map(|xs| {
18 | |                 xs.iter()
19 | |             })
20 | |     }
   | |_____^
```
[playground](https://play.rust-lang.org/?gist=bfbe000e14759b026f574efcd12e9c1b&version=nightly)

Returning an `Iterator` on `OrderMap` values would be a hugely useful tool for me to have, so figured I would see if perhaps some more experienced people here could show the right way. Thanks for any help you can provide.

**Comment by bluss** [comment]
Use into iter on option. On mobile, can't look into it more right now.

**Comment by jonathanstrong** [comment]
Amazing! Works like a charm. [playground](https://play.rust-lang.org/?gist=f040ed5056bb4cecf2dce750690d875a&version=nightly)

Here is the version of the function that works:

```
struct Map<T> {
    pub items: OrderMap<Uuid, Vec<T>>,
}

impl<T> Map<T> {
    fn iter_key<'a>(&'a self, k: &'a Uuid) -> impl Iterator<Item = &'a T> + 'a {
        self.items.get(k)
            .into_iter()
            .flat_map(|xs| xs.iter())
    }
}
```
Thanks!

**Comment by bluss** [comment]
Np
