### ISSUE TITLE
minor different behavior from HashMap

### ISSUE THREAD

**Issue by vitiral** [bluss/ordermap#54]
# summary
I'm not sure what the issue here is, but autodereferencing doesn't seem to be working for `&&T -> &T`

# example
I hit this while migratign from HashMap to OrderMap. I'm mostly opening this issue because I was confused about what was even happening and it might be useful to others. I was under the impression that rust did this kind of dereferencing automatically, but it appears not to be happening in this case.

The following code:
```
#[macro_use]
extern crate ordermap;

#[test]
fn test_it() {
    let key = "foo".to_string();
    let mut m = ordermap!{key.clone() => 3};
    assert!(m.contains_key(&&key));
}

fn main() {
    println!("yay");
}
```

results in this error:
```
error[E0277]: the trait bound `std::string::String: std::borrow::Borrow<&std::string::String>` is not satisfied
 --> src/main.rs:8:15
  |
8 |     assert!(m.contains_key(&&key));
  |               ^^^^^^^^^^^^ the trait `std::borrow::Borrow<&std::string::String>` is not implemented for `std::string::String`
  |
  = help: the following implementations were found:
            <std::string::String as std::borrow::Borrow<str>>
  = note: required because of the requirements on the impl of `ordermap::Equivalent<std::string::String>` for `&std::string::String`
```

**Comment by vitiral** [comment]
and... bizare... it seems like this doesn't work for HashMap either. And yet it only started breaking when I migrated. Closing

**Comment by bluss** [comment]
You are not imagining this. I believe it is fallout from the Borrow vs equivalent extension in ordermap. Since the Apis are type for type compatible but not 100% type inference compatible, I think it is acceptable
